### PR TITLE
Added mouse genome mm9

### PR DESCRIPTION
**Pull request by MikeDacre**
With this patch, CNVnator can now be used with the mouse mm9 genome. I can add mm10 if you wish also.

### CODE REVIEW

**Comment by MikeDacre** [comment]
I just realized that there are a few extra lines changed that I did not mean to change. This happened because my text editor auto-deletes trailing whitespace. I am just going to leave them like that, as it will not affect anything.

**Comment by abyzov** [comment]
Hi Mike,
by default genome info is parsed from sam/bam header. Did you have an essential need to encode mm9 genome into the soft?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745



On Jan 28, 2016, at 3:07 PM, Mike Dacre <notifications@github.com<mailto:notifications@github.com>> wrote:


I just realized that there are a few extra lines changed that I did not mean to change. This happened because my text editor auto-deletes trailing whitespace. I am just going to leave them like that, as it will not affect anything.

**Comment by MikeDacre** [comment]
Hi Alexej,

For me, I was getting an 'unknown genome' error without hardcoding the genome in, so I assumed it was required. Possibly there was some problem with my bam file headers.

-Mike

**Comment by abyzov** [comment]
OK. I’ve just merged branches.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745







On Jan 30, 2016, at 6:23 PM, Mike Dacre <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Alexej,

For me, I was getting an 'unknown genome' error without hardcoding the genome in, so I assumed it was required. Possibly there was some problem with my bam file headers.

-Mike

**Comment by abyzov** [comment]
Thanks for the improvements.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Pull request merged**
